### ISSUE TITLE
[web_notify] waiting for bus event to activate notification cause heating on mobile browser

### ISSUE THREAD

**Issue by hoangtrann** [OCA/web#1636]
**Description**

Recently I use `web_notify` on my implementation. This module works great on desktop browsers with no issue. But when I use the application on mobile device using the browser (Chrome, Firefox), I notice that the device would be heating really quick after 10-15s I start using the application. After uninstalling the module, there is no more heating issue on the device.

**Affected version**

12.0 (As I'm currently using this version)

**Comment by simahawk** [comment]
Can you provide more details? Eg: how are you using it?

**Comment by hoangtrann** [comment]
- I install `web_notify` on my implementation, note that I does not make any customization related to `bus.bus`
- Access the instance using browser on mobile (currently using Chrome/Firefox/Safari on iOS 13.5.1) and then I feel the back of my phone heating really quick. I use iPhone 11 Pro, and this issue seem to happen with Chrome, Firefox and Safari as I try them.
- This issue do happen with my Samsung Galaxy S9, but the heating is slower and doesn't feel as hot as the iPhone.

Fore more details, I just log-in into the instance, with the homepage is Discuss, and the heating start right away. The heating issue only goes away when I shut down the tab related to the instance. Issue happen both on local network and deployed environment

**Comment by simahawk** [comment]
@hoangtrann thanks for your info. Are you able to replicate this on runbot?

http://3431155-12-0-e81e23.runbot2-2.odoo-community.org/web/login?db=3431155-12-0-e81e23-all&login=admin&redirect=/web?debug=1

(TIP: you can find this link at the top of each module's README)

**Comment by hoangtrann** [comment]
@simahawk I confirm that this does happen when I entered the link above. The phone start heating within a few second after login

**Comment by simahawk** [comment]
@lmignon any experience w/ this issue?

**Comment by lmignon** [comment]
I never encountered this kind of issue but I never use a mobile to access to Odoo... The code is very simple and it's hard to imagine the origin of this issue....

**Comment by jjscarafia** [comment]
perhaps this can be linked to [this](https://github.com/OCA/web/pull/1531)?
I'm facing some issues with web_notify, specially on v13. I face exactly the same behavior explain here for v12 https://github.com/OCA/web/pull/1531 and also sometimes the connections get full and they are fixed by reloading all the tabs

**Comment by simahawk** [comment]
@jjscarafia thanks for the heads up. @hoangtrann could you test the fix done on #1531 ?

**Comment by hoangtrann** [comment]
@simahawk I applied the patch from the PR above, but this does not solve the issue. The device still heat up really fast, and I also notice that this issue does lead to a resources exhaustion server side. It fills up the connection pull very fast, and the server can't start new thread to handle other requests
```
2020-07-31 06:34:43,693 17159 INFO db werkzeug: 192.168.1.4 - - [31/Jul/2020 06:34:43] "POST /longpolling
/poll HTTP/1.1" 400 - 0 0.000 0.001                                                                                    
2020-07-31 06:34:43,698 17159 INFO db werkzeug: 192.168.1.4 - - [31/Jul/2020 06:34:43] "POST /longpolling
/poll HTTP/1.1" 400 - 0 0.000 0.002                                                                                    
2020-07-31 06:34:45,742 17159 DEBUG db odoo.modules.registry: Multiprocess signaling check: [Registry - 2
5 -> 25] [Cache - 504 -> 504]                                                                                          
2020-07-31 06:34:46,007 17159 DEBUG db odoo.modules.registry: Multiprocess signaling check: [Registry - 2
5 -> 25] [Cache - 504 -> 504]                                                                                          
2020-07-31 06:34:46,546 17159 DEBUG db odoo.modules.registry: Multiprocess signaling check: [Registry - 2
5 -> 25] [Cache - 504 -> 504]                                                                                          
2020-07-31 06:34:46,861 17159 DEBUG db odoo.modules.registry: Multiprocess signaling check: [Registry - 2
5 -> 25] [Cache - 504 -> 504]                                                                                          
2020-07-31 06:34:47,093 17159 DEBUG db odoo.modules.registry: Multiprocess signaling check: [Registry - 2
5 -> 25] [Cache - 504 -> 504]                                                                                          
2020-07-31 06:34:47,417 17159 DEBUG db odoo.modules.registry: Multiprocess signaling check: [Registry - 2
5 -> 25] [Cache - 504 -> 504]                                                                                          
2020-07-31 06:34:47,875 17159 DEBUG db odoo.modules.registry: Multiprocess signaling check: [Registry - 2
5 -> 25] [Cache - 504 -> 504]                                                                                          
2020-07-31 06:34:47,877 17159 DEBUG db odoo.modules.registry: Multiprocess signaling check: [Registry - 2
5 -> 25] [Cache - 504 -> 504]                                                                                          
2020-07-31 06:34:47,903 17159 INFO db odoo.service.model: SERIALIZATION_FAILURE, retry 1/5 in 0.8557 sec.
..   
```

```
2020-07-31 06:35:02,388 17159 ERROR ? odoo.service.server: Exception happened during processing of request from ('192.1
68.1.4', 49387)                                                                                                        
Traceback (most recent call last):                                                                                     
  File "/home/xxx/.pyenv/versions/3.6.9/lib/python3.6/socketserver.py", line 320, in _handle_request_noblock         
    self.process_request(request, client_address)                                                                      
  File "/home/xxx/apps/odoo12/odoo/service/server.py", line 170, in process_request                                  
    t.start()                                                                                                          
  File "/home/xxx/.pyenv/versions/3.6.9/lib/python3.6/threading.py", line 846, in start                              
    _start_new_thread(self._bootstrap, ())                                                                             
RuntimeError: can't start new thread     
```

**Comment by hoangtrann** [comment]
This issue seems to happen on iOS but not on Android. I tested on Chrome, Firefox and Safari with the following result:

- Chrome, Firefox on iOS: the device heats up quickly, resource exhaustion happen on both client and server side.
- Chrome, Firefox on Android: work well with no issue of resource exhaustion.
- Safari, as this only run on iOS: the device heat up, but no resource exhaustion on server side.

**Comment by hoangtrann** [comment]
After some further investigation, I think that the issue happened due too the crosstab feature, which store and compare channels using local storage, as already mention in the PR above. There might be some issues with local storage while setting and getting the channels, which lead to the recursive set-get channels on the client side. These issues only happened on iOS devices (iphone in this case), so my suggestion is that we will not implement this feature for mobile device, or the iOS devices. Due to the fact that this can cause serious problems for the server side, so we should prevent it.

What do you think about this @simahawk ?

**Comment by hoangtrann** [comment]
I submit [PR](https://github.com/odoo/odoo/pull/55654) to fix this issue, as the `StorageEvent` is fired in the same tab where we add channels to poll. This behavior happened in browser running on iOS mobile devices.

**Comment by hoangtrann** [comment]
Close since this isn't specifically related to this module
